part_one:
	python3 -c "from challenges import part_one; result = part_one(); print(result)"

part_two:
	python3 -c "from challenges import part_two; result = part_two(); print(result)"

test:
	python3 -m unittest