day_one_part_one:
	python3 -c "from challenges import day_one_part_one; result = day_one_part_one(); print(result)"

day_one_part_two:
	python3 -c "from challenges import day_one_part_two; result = day_one_part_two(); print(result)"

test:
	python3 -m unittest